# Generated by Django 6.0.6 on 2026-07-11 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha01Territorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastoral_zone', models.CharField(max_length=100)),
                ('parish_sector', models.CharField(max_length=150)),
                ('survey_date', models.DateField()),
                ('survey_responsible', models.CharField(max_length=150)),
                ('parish_priest', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=50)),
                ('official_parish_name', models.CharField(max_length=200)),
                ('church_advocation', models.CharField(blank=True, max_length=200, null=True)),
                ('civil_municipality', models.CharField(max_length=200)),
                ('influence_radius', models.CharField(max_length=100)),
                ('estimated_population', models.IntegerField()),
                ('estimated_households', models.IntegerField()),
                ('gps_coordinates', models.CharField(max_length=100)),
                ('main_accessibility', models.TextField()),
                ('territory_type', models.JSONField(default=list)),
                ('kobo_uuid', models.UUIDField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Ficha 1 - Identificación Territorial',
                'verbose_name_plural': 'Ficha 1 - Identificaciones Territoriales',
            },
        ),
        migrations.CreateModel(
            name='Ficha01CoveredCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_sector', models.CharField(max_length=200)),
                ('estimated_community_population', models.IntegerField(blank=True, null=True)),
                ('distance_time_to_church', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('territory_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_communities', to='kobo.ficha01territorio')),
            ],
            options={
                'verbose_name': 'Comunidad Cubierta',
                'verbose_name_plural': 'Comunidades Cubiertas',
            },
        ),
        migrations.CreateModel(
            name='KoboFormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('schema_snapshot', models.JSONField(default=dict)),
                ('field_mapping', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('form_id', 'version'),
                'constraints': [models.UniqueConstraint(fields=('form_id', 'version'), name='kobo_unique_form_version')],
            },
        ),
        migrations.CreateModel(
            name='KoboSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('normalized', 'Normalized'), ('validation_failed', 'Validation failed'), ('ready_for_review', 'Ready for review'), ('approved_for_import', 'Approved for import'), ('imported', 'Imported'), ('partially_imported', 'Partially imported'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('processing_failed', 'Processing failed')], default='received', max_length=32)),
                ('pastoral_zone', models.CharField(blank=True, max_length=255)),
                ('parish', models.CharField(blank=True, max_length=255)),
                ('primary_community', models.CharField(blank=True, max_length=255)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='kobo.koboformdefinition')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='KoboProcessingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=16)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_events', to='kobo.kobosubmission')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='KoboAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='kobo/attachments/')),
                ('privacy_level', models.CharField(choices=[('private', 'Private'), ('internal_review', 'Internal review'), ('public_candidate', 'Public candidate')], default='internal_review', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloaded', 'Downloaded'), ('invalid', 'Invalid'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kobo.kobosubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='kobosubmission',
            constraint=models.UniqueConstraint(fields=('form_definition', 'external_id'), name='kobo_unique_external_submission_per_form'),
        ),
    ]
