# Generated by Django 6.0.6 on 2026-07-11 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0001_initial'),
        ('operations', '0003_alter_donation_donation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_uid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('form_role', models.CharField(choices=[('territorial_profile', 'Territorial profile'), ('prioritized_microproject', 'Prioritized microproject'), ('prioritization_matrix', 'Prioritization matrix')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='kobo.koboformdefinition')),
            ],
            options={
                'ordering': ('name', 'asset_uid'),
            },
        ),
        migrations.CreateModel(
            name='KoboProjectBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastoral_zone', models.CharField(choices=[('catia_la_mar', 'Catia La Mar'), ('centro', 'Centro'), ('este', 'Este'), ('montana', 'Montaña'), ('insular', 'Insular')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bindings', to='kobo.koboasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kobo_bindings', to='operations.project')),
            ],
            options={
                'ordering': ('asset', 'pastoral_zone'),
            },
        ),
        migrations.AddConstraint(
            model_name='koboasset',
            constraint=models.CheckConstraint(condition=models.Q(('form_role__in', ('territorial_profile', 'prioritized_microproject', 'prioritization_matrix'))), name='kobo_asset_valid_form_role'),
        ),
        migrations.AddConstraint(
            model_name='koboprojectbinding',
            constraint=models.UniqueConstraint(fields=('asset', 'pastoral_zone'), name='kobo_unique_asset_pastoral_zone'),
        ),
        migrations.AddConstraint(
            model_name='koboprojectbinding',
            constraint=models.UniqueConstraint(fields=('asset', 'project'), name='kobo_unique_asset_project'),
        ),
        migrations.AddConstraint(
            model_name='koboprojectbinding',
            constraint=models.CheckConstraint(condition=models.Q(('pastoral_zone__in', ('catia_la_mar', 'centro', 'este', 'montana', 'insular'))), name='kobo_binding_valid_pastoral_zone'),
        ),
    ]
