# Generated by Django 6.0.6 on 2026-07-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0002_koboasset_koboprojectbinding_and_more'),
        ('operations', '0003_alter_donation_donation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kobosubmission',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='kobo.koboasset'),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kobo_submissions', to='operations.project'),
        ),
    ]
