# Generated by Django 6.0.6 on 2026-07-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0004_generic_project_binding_routing'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboDiscoveredAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_uid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(blank=True, max_length=100)),
                ('deployment_status', models.CharField(blank=True, max_length=100)),
                ('owner_username', models.CharField(blank=True, max_length=255)),
                ('remote_created_at', models.DateTimeField(blank=True, null=True)),
                ('remote_modified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_snapshot', models.JSONField(default=dict)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'asset_uid'),
            },
        ),
    ]
