# Generated by Django 6.0.6 on 2026-07-19 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0006_koboattachment_processing_claim'),
        ('operations', '0020_alter_auditlog_action_projectmilestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboPastoralZoneProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastoral_zone', models.CharField(choices=[('catia_la_mar', 'Catia La Mar'), ('centro', 'Centro'), ('este', 'Este'), ('montana', 'Montana'), ('insular', 'Insular')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('pastoral_zone', '-is_active'),
            },
        ),
        migrations.CreateModel(
            name='KoboTerritorialIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucleo_code_original', models.CharField(max_length=255)),
                ('nucleo_code_normalized', models.CharField(max_length=255, unique=True)),
                ('pastoral_zone', models.CharField(choices=[('catia_la_mar', 'Catia La Mar'), ('centro', 'Centro'), ('este', 'Este'), ('montana', 'Montana'), ('insular', 'Insular')], max_length=32)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('active', 'Active'), ('observed', 'Observed'), ('inactive', 'Inactive')], default='pending_review', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nucleo_code_normalized',),
            },
        ),
        migrations.CreateModel(
            name='KoboTerritorialIdentityConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existing_pastoral_zone', models.CharField(choices=[('catia_la_mar', 'Catia La Mar'), ('centro', 'Centro'), ('este', 'Este'), ('montana', 'Montana'), ('insular', 'Insular')], max_length=32)),
                ('proposed_pastoral_zone', models.CharField(choices=[('catia_la_mar', 'Catia La Mar'), ('centro', 'Centro'), ('este', 'Este'), ('montana', 'Montana'), ('insular', 'Insular')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved_keep_existing', 'Resolved: keep existing'), ('resolved_accept_proposed', 'Resolved: accept proposed'), ('dismissed', 'Dismissed')], default='open', max_length=32)),
                ('resolution', models.CharField(blank=True, choices=[('keep_existing', 'Keep existing'), ('accept_proposed', 'Accept proposed'), ('dismissed', 'Dismissed')], max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='nucleo_code_normalized',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='nucleo_code_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='routing_reason_code',
            field=models.CharField(blank=True, choices=[('missing_nucleo_code', 'missing_nucleo_code'), ('invalid_nucleo_code', 'invalid_nucleo_code'), ('missing_pastoral_zone', 'missing_pastoral_zone'), ('invalid_pastoral_zone', 'invalid_pastoral_zone'), ('unknown_territorial_identity', 'unknown_territorial_identity'), ('territorial_identity_conflict', 'territorial_identity_conflict'), ('unsupported_form', 'unsupported_form')], max_length=100),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='routing_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='routing_status',
            field=models.CharField(choices=[('unresolved', 'Unresolved'), ('pending_identity', 'Pending identity'), ('resolved', 'Resolved'), ('conflict', 'Conflict'), ('error', 'Error')], default='unresolved', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='kobosubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('routing_status', 'resolved'), _negated=True), ('project__isnull', False), _connector='OR'), name='kobo_resolved_routing_requires_project'),
        ),
        migrations.AddConstraint(
            model_name='kobosubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('routing_status', 'pending_identity'), _negated=True), ('project__isnull', True), _connector='OR'), name='kobo_pending_identity_has_no_project'),
        ),
        migrations.AddField(
            model_name='kobopastoralzoneprojectmapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kobo_pastoral_zone_mappings', to='operations.project'),
        ),
        migrations.AddField(
            model_name='koboterritorialidentity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kobo_territorial_identities', to='operations.project'),
        ),
        migrations.AddField(
            model_name='koboterritorialidentity',
            name='source_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_territorial_identities', to='kobo.kobosubmission'),
        ),
        migrations.AddField(
            model_name='koboterritorialidentityconflict',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts', to='kobo.koboterritorialidentity'),
        ),
        migrations.AddField(
            model_name='koboterritorialidentityconflict',
            name='incoming_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='territorial_identity_conflicts', to='kobo.kobosubmission'),
        ),
        migrations.AddField(
            model_name='koboterritorialidentityconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_kobo_territorial_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='kobopastoralzoneprojectmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('pastoral_zone',), name='kobo_unique_active_zone_project_mapping'),
        ),
        migrations.AddConstraint(
            model_name='kobopastoralzoneprojectmapping',
            constraint=models.CheckConstraint(condition=models.Q(('pastoral_zone__in', ('catia_la_mar', 'centro', 'este', 'montana', 'insular'))), name='kobo_mapping_valid_pastoral_zone'),
        ),
        migrations.AddIndex(
            model_name='koboterritorialidentity',
            index=models.Index(fields=['pastoral_zone', 'status'], name='kobo_identity_zone_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='koboterritorialidentity',
            constraint=models.CheckConstraint(condition=models.Q(('nucleo_code_original', ''), _negated=True), name='kobo_identity_original_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='koboterritorialidentity',
            constraint=models.CheckConstraint(condition=models.Q(('nucleo_code_normalized', ''), _negated=True), name='kobo_identity_normalized_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='koboterritorialidentity',
            constraint=models.CheckConstraint(condition=models.Q(('pastoral_zone__in', ('catia_la_mar', 'centro', 'este', 'montana', 'insular'))), name='kobo_identity_valid_pastoral_zone'),
        ),
        migrations.AddIndex(
            model_name='koboterritorialidentityconflict',
            index=models.Index(fields=['status', 'proposed_pastoral_zone'], name='kobo_conflict_status_zone_idx'),
        ),
        migrations.AddConstraint(
            model_name='koboterritorialidentityconflict',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('identity', 'incoming_submission', 'proposed_pastoral_zone'), name='kobo_unique_open_territorial_conflict'),
        ),
        migrations.AddConstraint(
            model_name='koboterritorialidentityconflict',
            constraint=models.CheckConstraint(condition=models.Q(('existing_pastoral_zone__in', ('catia_la_mar', 'centro', 'este', 'montana', 'insular'))), name='kobo_conflict_valid_existing_zone'),
        ),
        migrations.AddConstraint(
            model_name='koboterritorialidentityconflict',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_pastoral_zone__in', ('catia_la_mar', 'centro', 'este', 'montana', 'insular'))), name='kobo_conflict_valid_proposed_zone'),
        ),
    ]
