# Generated by Django 6.0.6 on 2026-07-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0008_add_missing_zone_project_mapping_reason'),
        ('operations', '0020_alter_auditlog_action_projectmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='koboterritorialidentityconflict',
            name='existing_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='existing_kobo_territorial_identity_conflicts', to='operations.project'),
        ),
        migrations.AddField(
            model_name='koboterritorialidentityconflict',
            name='proposed_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_kobo_territorial_identity_conflicts', to='operations.project'),
        ),
    ]
