# Generated by Django 6.0.6 on 2026-07-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kobo", "0009_capture_territorial_conflict_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kobosubmission",
            name="routing_reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("missing_nucleo_code", "missing_nucleo_code"),
                    ("invalid_nucleo_code", "invalid_nucleo_code"),
                    ("missing_pastoral_zone", "missing_pastoral_zone"),
                    ("invalid_pastoral_zone", "invalid_pastoral_zone"),
                    (
                        "unknown_territorial_identity",
                        "unknown_territorial_identity",
                    ),
                    (
                        "territorial_identity_invalid",
                        "territorial_identity_invalid",
                    ),
                    (
                        "territorial_identity_conflict",
                        "territorial_identity_conflict",
                    ),
                    (
                        "missing_zone_project_mapping",
                        "missing_zone_project_mapping",
                    ),
                    ("unsupported_form", "unsupported_form"),
                ],
                max_length=100,
            ),
        ),
    ]
