# Generated by Django 6.0.6 on 2026-07-20 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0010_alter_kobosubmission_routing_reason_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_type', models.CharField(max_length=32)),
                ('target_app_label', models.CharField(max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('target_object_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kobo_import_records', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='import_record', to='kobo.kobosubmission')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('target_object_id__gt', 0)), name='kobo_import_record_positive_target_id')],
            },
        ),
    ]
