# Generated by Django 6.0.6 on 2026-07-20 15:58

import apps.integrations.kobo.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kobo", "0011_koboimportrecord"),
        ("operations", "0020_alter_auditlog_action_projectmilestone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="koboprocessingevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="KoboTerritorialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parish", models.CharField(max_length=255)),
                ("community_sector", models.CharField(max_length=255)),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[
                            apps.integrations.kobo.models.validate_territorial_profile_location
                        ],
                    ),
                ),
                ("parish_delegate", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=100)),
                (
                    "main_informant_role",
                    models.CharField(blank=True, max_length=255),
                ),
                ("communities_covered", models.TextField(blank=True)),
                (
                    "estimated_households",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "access_difficulties",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("access_difficulties_notes", models.TextField(blank=True)),
                (
                    "initial_priority_perception",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("general_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_kobo_territorial_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kobo_territorial_profiles",
                        to="operations.project",
                    ),
                ),
                (
                    "source_submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="territorial_profile",
                        to="kobo.kobosubmission",
                    ),
                ),
                (
                    "territorial_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="territorial_profiles",
                        to="kobo.koboterritorialidentity",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["territorial_identity", "-created_at"],
                        name="kobo_prof_identity_date_idx",
                    ),
                    models.Index(
                        fields=["project", "-created_at"],
                        name="kobo_prof_project_date_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("estimated_households__isnull", True),
                            ("estimated_households__gte", 0),
                            _connector="OR",
                        ),
                        name="kobo_profile_households_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("access_difficulties__in", ("yes", "no", "unknown"))
                        ),
                        name="kobo_profile_valid_access_difficulty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "initial_priority_perception__in",
                                ("low", "medium", "high", "critical", "unknown"),
                            )
                        ),
                        name="kobo_profile_valid_priority",
                    ),
                ],
            },
        ),
    ]
