# Generated by Django 6.0.6 on 2026-07-20 16:45

import apps.integrations.kobo.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0012_koboprocessingevent_metadata_koboterritorialprofile'),
        ('operations', '0020_alter_auditlog_action_projectmilestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboPrioritizedMicroproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('component', models.CharField(choices=[('communication', 'Communication'), ('health_psychosocial', 'Health Psychosocial'), ('infrastructure', 'Infrastructure'), ('livelihoods', 'Livelihoods'), ('mixed', 'Mixed'), ('training', 'Training')], max_length=32)),
                ('problem_summary', models.TextField()),
                ('specific_objective', models.TextField()),
                ('beneficiary_group', models.JSONField(validators=[apps.integrations.kobo.models.validate_prioritized_microproject_beneficiary_groups])),
                ('main_activities', models.TextField()),
                ('estimated_cost_range', models.CharField(choices=[('1000_5000', '1000 5000'), ('15000_50000', '15000 50000'), ('5000_15000', '5000 15000'), ('over_50000', 'Over 50000'), ('under_1000', 'Under 1000'), ('unknown', 'Unknown')], max_length=32)),
                ('implementation_urgency', models.CharField(choices=[('follow_up', 'Follow Up'), ('immediate', 'Immediate'), ('medium_term', 'Medium Term'), ('short_term', 'Short Term'), ('unknown', 'Unknown')], max_length=32)),
                ('technical_viability', models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium'), ('not_viable', 'Not Viable'), ('requires_design', 'Requires Design')], max_length=32)),
                ('expected_result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_kobo_prioritized_microprojects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kobo_prioritized_microprojects', to='operations.project')),
                ('source_submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prioritized_microproject', to='kobo.kobosubmission')),
                ('territorial_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prioritized_microprojects', to='kobo.koboterritorialidentity')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['territorial_identity', '-created_at'], name='kobo_micro_identity_date_idx'), models.Index(fields=['project', '-created_at'], name='kobo_micro_project_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='kobo_microproject_name_not_empty'), models.CheckConstraint(condition=models.Q(('problem_summary', ''), _negated=True), name='kobo_microproject_problem_not_empty'), models.CheckConstraint(condition=models.Q(('specific_objective', ''), _negated=True), name='kobo_microproject_objective_not_empty'), models.CheckConstraint(condition=models.Q(('main_activities', ''), _negated=True), name='kobo_microproject_activities_not_empty'), models.CheckConstraint(condition=models.Q(('expected_result', ''), _negated=True), name='kobo_microproject_result_not_empty'), models.CheckConstraint(condition=models.Q(('component__in', ('communication', 'health_psychosocial', 'infrastructure', 'livelihoods', 'mixed', 'training'))), name='kobo_microproject_valid_component'), models.CheckConstraint(condition=models.Q(('estimated_cost_range__in', ('1000_5000', '15000_50000', '5000_15000', 'over_50000', 'under_1000', 'unknown'))), name='kobo_microproject_valid_cost_range'), models.CheckConstraint(condition=models.Q(('implementation_urgency__in', ('follow_up', 'immediate', 'medium_term', 'short_term', 'unknown'))), name='kobo_microproject_valid_urgency'), models.CheckConstraint(condition=models.Q(('technical_viability__in', ('high', 'low', 'medium', 'not_viable', 'requires_design'))), name='kobo_microproject_valid_viability')],
            },
        ),
    ]
