# Generated by Django 6.0.6 on 2026-07-20 17:21

import apps.integrations.kobo.models
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0013_koboprioritizedmicroproject'),
        ('operations', '0020_alter_auditlog_action_projectmilestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboPrioritizationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_damage_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('affected_families_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('social_vulnerability_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('services_interruption_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('livelihood_loss_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('parish_capacity_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('territorial_accessibility_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('allies_availability_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rapid_impact_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('financial_viability_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('priority_total_original', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority_total_calculated', models.PositiveSmallIntegerField()),
                ('suggested_semaphore_original', models.CharField(blank=True, choices=[('gray', 'Gray'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow')], max_length=16)),
                ('suggested_semaphore_calculated', models.CharField(choices=[('gray', 'Gray'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow')], max_length=16)),
                ('final_semaphore', models.CharField(choices=[('gray', 'Gray'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow')], max_length=16)),
                ('final_priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('low', 'Low'), ('medium', 'Medium'), ('unknown', 'Unknown')], max_length=16)),
                ('priority_summary', models.TextField()),
                ('calculation_warnings', models.JSONField(blank=True, default=list, validators=[apps.integrations.kobo.models.validate_prioritization_calculation_warnings])),
                ('linked_microprojects_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_kobo_prioritization_assessments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kobo_prioritization_assessments', to='operations.project')),
                ('source_submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prioritization_assessment', to='kobo.kobosubmission')),
                ('territorial_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prioritization_assessments', to='kobo.koboterritorialidentity')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['territorial_identity', '-created_at'], name='kobo_assess_identity_date_idx'), models.Index(fields=['project', '-created_at'], name='kobo_assess_project_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('affected_families_score__range', (1, 5)), ('allies_availability_score__range', (1, 5)), ('financial_viability_score__range', (1, 5)), ('livelihood_loss_score__range', (1, 5)), ('parish_capacity_score__range', (1, 5)), ('physical_damage_score__range', (1, 5)), ('rapid_impact_score__range', (1, 5)), ('services_interruption_score__range', (1, 5)), ('social_vulnerability_score__range', (1, 5)), ('territorial_accessibility_score__range', (1, 5))), name='kobo_assessment_scores_in_range'), models.CheckConstraint(condition=models.Q(('priority_total_calculated', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('physical_damage_score'), '+', models.F('affected_families_score')), '+', models.F('social_vulnerability_score')), '+', models.F('services_interruption_score')), '+', models.F('livelihood_loss_score')), '+', models.F('parish_capacity_score')), '+', models.F('territorial_accessibility_score')), '+', models.F('allies_availability_score')), '+', models.F('rapid_impact_score')), '+', models.F('financial_viability_score')))), name='kobo_assessment_total_matches_scores'), models.CheckConstraint(condition=models.Q(('suggested_semaphore_original', ''), ('suggested_semaphore_original__in', ('gray', 'green', 'red', 'yellow')), _connector='OR'), name='kobo_assessment_valid_original_semaphore'), models.CheckConstraint(condition=models.Q(('suggested_semaphore_calculated__in', ('gray', 'green', 'red', 'yellow'))), name='kobo_assessment_valid_calculated_semaphore'), models.CheckConstraint(condition=models.Q(('final_semaphore__in', ('gray', 'green', 'red', 'yellow'))), name='kobo_assessment_valid_final_semaphore'), models.CheckConstraint(condition=models.Q(('final_priority__in', ('critical', 'high', 'low', 'medium', 'unknown'))), name='kobo_assessment_valid_final_priority'), models.CheckConstraint(condition=models.Q(('priority_summary', ''), _negated=True), name='kobo_assessment_summary_not_empty')],
            },
        ),
    ]
