# Generated by Django 6.0.6 on 2026-07-20 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0014_koboprioritizationassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kobopastoralzoneprojectmapping',
            options={'ordering': ('pastoral_zone', '-is_active'), 'permissions': [('manage_pastoral_zone_mappings', 'Can manage pastoral-zone project mappings')]},
        ),
        migrations.AlterModelOptions(
            name='koboterritorialidentity',
            options={'ordering': ('nucleo_code_normalized',), 'permissions': [('view_territorial_administration', 'Can view territorial administration'), ('change_territorial_identity_status', 'Can change territorial identity status'), ('run_territorial_reconciliation', 'Can run territorial reconciliation')]},
        ),
        migrations.AlterModelOptions(
            name='koboterritorialidentityconflict',
            options={'ordering': ('-created_at',), 'permissions': [('resolve_territorial_conflicts', 'Can resolve territorial conflicts')]},
        ),
        migrations.AddField(
            model_name='kobopastoralzoneprojectmapping',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kobopastoralzoneprojectmapping',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_kobo_pastoral_zone_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kobopastoralzoneprojectmapping',
            name='deactivation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='koboterritorialidentityconflict',
            name='resolution_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kobosubmission',
            name='routing_reason_code',
            field=models.CharField(blank=True, choices=[('missing_nucleo_code', 'missing_nucleo_code'), ('invalid_nucleo_code', 'invalid_nucleo_code'), ('missing_pastoral_zone', 'missing_pastoral_zone'), ('invalid_pastoral_zone', 'invalid_pastoral_zone'), ('unknown_territorial_identity', 'unknown_territorial_identity'), ('territorial_identity_invalid', 'territorial_identity_invalid'), ('territorial_identity_conflict', 'territorial_identity_conflict'), ('missing_zone_project_mapping', 'missing_zone_project_mapping'), ('unsupported_form', 'unsupported_form'), ('territorial_conflict_rejected', 'territorial_conflict_rejected')], max_length=100),
        ),
        migrations.CreateModel(
            name='KoboTerritorialAdministrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kobo_territorial_administration_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
