# Generated by Django 6.0.6 on 2026-07-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0016_kobo_sync_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='koboasset',
            name='last_remote_watermark',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='koboasset',
            name='last_successful_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='koboasset',
            name='last_successful_sync_cursor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='koboasset',
            name='sync_lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='koboasset',
            name='sync_lease_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='last_remote_payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='remote_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='remote_update_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='remote_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kobosubmission',
            name='remote_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kobosyncrun',
            name='cursor_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kobosyncrun',
            name='cursor_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kobosyncrun',
            name='items_unchanged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kobosyncrun',
            name='lease_recovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kobosyncrun',
            name='mode',
            field=models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], default='full', max_length=16),
        ),
        migrations.AddField(
            model_name='kobosyncrun',
            name='remote_updates_detected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kobosyncrun',
            name='watermark_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kobosyncrun',
            name='watermark_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kobosyncrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='running', max_length=16),
        ),
        migrations.CreateModel(
            name='KoboSubmissionRemoteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_version', models.CharField(blank=True, max_length=255)),
                ('remote_updated_at', models.DateTimeField(blank=True, null=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('applied', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remote_revisions', to='kobo.kobosubmission')),
            ],
            options={
                'ordering': ('-received_at',),
                'constraints': [models.UniqueConstraint(fields=('submission', 'payload_hash'), name='kobo_unique_remote_revision_hash')],
            },
        ),
    ]
