# Generated by Django 6.0.6 on 2026-07-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0017_incremental_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='koboasset',
            name='sync_lease_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leased_assets', to='kobo.kobosyncrun'),
        ),
    ]
