from django.urls import path

from apps.integrations.kobo import views

app_name = "kobo"
urlpatterns = [
    path("webhook/", views.webhook_submission, name="webhook_submission"),
    path(
        "discovered-assets/",
        views.discovered_asset_list,
        name="discovered_asset_list",
    ),
    path(
        "discovered-assets/<int:pk>/",
        views.discovered_asset_detail,
        name="discovered_asset_detail",
    ),
    path(
        "discovered-assets/<int:pk>/configure/",
        views.configure_discovered_asset_action,
        name="configure_discovered_asset",
    ),
    path(
        "assets/<int:pk>/configuration/",
        views.asset_configuration_detail,
        name="asset_configuration",
    ),
    path(
        "assets/<int:pk>/bindings/",
        views.create_project_binding_action,
        name="create_project_binding",
    ),
    path(
        "assets/<int:pk>/activate/",
        views.activate_kobo_asset_action,
        name="activate_asset",
    ),
    path(
        "assets/<int:pk>/deactivate/",
        views.deactivate_kobo_asset_action,
        name="deactivate_asset",
    ),
    path(
        "project-submissions/<int:pk>/",
        views.project_submission_detail,
        name="project_submission_detail",
    ),
    path(
        "project-submissions/<int:pk>/evidence/<int:attachment_pk>/",
        views.project_submission_evidence,
        name="project_submission_evidence",
    ),
    path(
        "projects/<int:project_pk>/pending-submissions/",
        views.project_pending_submission_list,
        name="project_pending_submission_list",
    ),
    path(
        "projects/<int:project_pk>/pending-submissions/<int:pk>/",
        views.project_pending_submission_review,
        name="project_pending_submission_review",
    ),
    path(
        "projects/<int:project_pk>/pending-submissions/<int:pk>/import/",
        views.project_pending_submission_import,
        name="project_pending_submission_import",
    ),
    path(
        "projects/<int:project_pk>/pending-submissions/<int:pk>/reject/",
        views.project_pending_submission_reject,
        name="project_pending_submission_reject",
    ),
    path(
        "projects/<int:project_pk>/submission-history/",
        views.project_submission_history,
        name="project_submission_history",
    ),
    path(
        "projects/<int:project_pk>/submission-history/<int:pk>/",
        views.project_submission_history_detail,
        name="project_submission_history_detail",
    ),
    path(
        "projects/<int:project_pk>/submission-history/<int:pk>/restore/",
        views.project_rejected_submission_restore,
        name="project_rejected_submission_restore",
    ),
    path("submissions/", views.submission_list, name="submission_list"),
    path(
        "submissions/<int:pk>/",
        views.submission_detail,
        name="submission_detail",
    ),
    path(
        "submissions/<int:pk>/review/",
        views.review_submission_action,
        name="submission_review",
    ),
    path(
        "submissions/<int:pk>/retry-normalization/",
        views.retry_normalization_action,
        name="submission_retry_normalization",
    ),
    path(
        "submissions/<int:pk>/retry-attachments/",
        views.retry_attachments_action,
        name="submission_retry_attachments",
    ),
    path(
        "submissions/<int:pk>/associate-project/",
        views.associate_project_action,
        name="submission_associate_project",
    ),
]
