from django.urls import path

from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('institutions/', views.InstitutionListView.as_view(), name='institution_list'),
    path('institutions/new/', views.InstitutionCreateView.as_view(), name='institution_create'),
    path('institutions/<int:pk>/', views.InstitutionDetailView.as_view(), name='institution_detail'),
    path(
        'institutions/<int:pk>/legal-document/download/',
        views.InstitutionLegalDocumentDownloadView.as_view(),
        name='institution_legal_document_download',
    ),
    path('institutions/<int:pk>/edit/', views.InstitutionUpdateView.as_view(), name='institution_update'),
    path('institutions/<int:pk>/delete/', views.InstitutionDeleteView.as_view(), name='institution_delete'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/new/', views.ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('projects/<int:pk>/status/<str:target_status>/', views.ProjectStatusTransitionView.as_view(), name='project_status_transition'),
    path(
        'projects/<int:project_pk>/updates/create/',
        views.ProjectUpdateCreateForProjectView.as_view(),
        name='project_update_create_for_project',
    ),
    path('updates/', views.ProjectUpdateListView.as_view(), name='project_update_list'),
    path('updates/create/', views.ProjectUpdateCreateView.as_view(), name='project_update_create'),
    path('updates/<int:pk>/', views.ProjectUpdateDetailView.as_view(), name='project_update_detail'),
    path(
        'project-updates/<int:pk>/evidence/download/',
        views.ProjectUpdateEvidenceDownloadView.as_view(),
        name='project_update_evidence_download',
    ),
    path('updates/<int:pk>/edit/', views.ProjectUpdateUpdateView.as_view(), name='project_update_update'),
    path('updates/<int:pk>/review/', views.ProjectUpdateReviewView.as_view(), name='project_update_review'),
    path('updates/<int:pk>/delete/', views.ProjectUpdateDeleteView.as_view(), name='project_update_delete'),
    path('donations/', views.DonationListView.as_view(), name='donation_list'),
    path('donations/new/', views.DonationCreateView.as_view(), name='donation_create'),
    path('donations/<int:pk>/', views.DonationDetailView.as_view(), name='donation_detail'),
    path('donations/<int:pk>/edit/', views.DonationUpdateView.as_view(), name='donation_update'),
    path('donations/<int:pk>/delete/', views.DonationDeleteView.as_view(), name='donation_delete'),
    path('donations/<int:pk>/status/<str:target_status>/', views.DonationStatusTransitionView.as_view(), name='donation_status_transition'),
    path('allocations/', views.FundAllocationListView.as_view(), name='allocation_list'),
    path('allocations/new/', views.FundAllocationCreateView.as_view(), name='allocation_create'),
    path('allocations/<int:pk>/', views.FundAllocationDetailView.as_view(), name='allocation_detail'),
    path('allocations/<int:pk>/edit/', views.FundAllocationUpdateView.as_view(), name='allocation_update'),
    path('allocations/<int:pk>/delete/', views.FundAllocationDeleteView.as_view(), name='allocation_delete'),
    path('allocations/<int:pk>/status/<str:target_status>/', views.FundAllocationStatusTransitionView.as_view(), name='allocation_status_transition'),
    path('expenses/', views.ExpenseListView.as_view(), name='expense_list'),
    path('expenses/new/', views.ExpenseCreateView.as_view(), name='expense_create'),
    path('expenses/<int:pk>/', views.ExpenseDetailView.as_view(), name='expense_detail'),
    path('expenses/<int:pk>/edit/', views.ExpenseUpdateView.as_view(), name='expense_update'),
    path('expenses/<int:pk>/delete/', views.ExpenseDeleteView.as_view(), name='expense_delete'),
    path('expenses/<int:pk>/cancel/', views.ExpenseCancellationView.as_view(), name='expense_cancel'),
    path(
        'expenses/<int:expense_pk>/documents/create/',
        views.SupportingDocumentCreateForExpenseView.as_view(),
        name='supporting_document_create_for_expense',
    ),
    path(
        'documents/<int:pk>/download/',
        views.SupportingDocumentDownloadView.as_view(),
        name='supporting_document_download',
    ),
    path(
        'documents/<int:pk>/delete/',
        views.SupportingDocumentDeleteView.as_view(),
        name='supporting_document_delete',
    ),
    path('audit/', views.AuditLogListView.as_view(), name='audit_log_list'),
]
