from django.urls import path

from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('institutions/', views.InstitutionListView.as_view(), name='institution_list'),
    path('institutions/new/', views.InstitutionCreateView.as_view(), name='institution_create'),
    path('institutions/<int:pk>/', views.InstitutionDetailView.as_view(), name='institution_detail'),
    path(
        'institutions/<int:pk>/legal-document/preview/',
        views.InstitutionLegalDocumentPreviewView.as_view(),
        name='institution_legal_document_preview',
    ),
    path(
        'institutions/<int:pk>/legal-document/download/',
        views.InstitutionLegalDocumentDownloadView.as_view(),
        name='institution_legal_document_download',
    ),
    path('institutions/<int:pk>/edit/', views.InstitutionUpdateView.as_view(), name='institution_update'),
    path('institutions/<int:pk>/delete/', views.InstitutionDeleteView.as_view(), name='institution_delete'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/export.csv', views.ProjectCsvExportView.as_view(), name='project_export_csv'),
    path('projects/new/', views.ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path(
        'projects/<int:project_pk>/updates/chunk/',
        views.ProjectUpdateChunkView.as_view(),
        name='project_update_chunk',
    ),
    path('projects/<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:pk>/finish/', views.ProjectFinishView.as_view(), name='project_finish'),
    path('projects/<int:pk>/publish/', views.ProjectPublishView.as_view(), name='project_publish'),
    path(
        'projects/<int:pk>/unpublish/',
        views.ProjectUnpublishView.as_view(),
        name='project_unpublish',
    ),
    path(
        'projects/<int:project_pk>/milestones/add/',
        views.ProjectMilestoneAddView.as_view(),
        name='project_milestone_add',
    ),
    path(
        'milestones/<int:pk>/edit/',
        views.ProjectMilestoneEditView.as_view(),
        name='project_milestone_edit',
    ),
    path(
        'milestones/<int:pk>/complete/',
        views.ProjectMilestoneCompleteView.as_view(),
        name='project_milestone_complete',
    ),
    path(
        'milestones/<int:pk>/reopen/',
        views.ProjectMilestoneReopenView.as_view(),
        name='project_milestone_reopen',
    ),
    path(
        'milestones/<int:pk>/delete/',
        views.ProjectMilestoneDeleteView.as_view(),
        name='project_milestone_delete',
    ),
    path(
        'milestones/<int:pk>/move-up/',
        views.ProjectMilestoneMoveUpView.as_view(),
        name='project_milestone_move_up',
    ),
    path(
        'milestones/<int:pk>/move-down/',
        views.ProjectMilestoneMoveDownView.as_view(),
        name='project_milestone_move_down',
    ),
    path(
        'projects/<int:project_pk>/updates/create/',
        views.ProjectUpdateCreateForProjectView.as_view(),
        name='project_update_create_for_project',
    ),
    path('updates/', views.ProjectUpdateListView.as_view(), name='project_update_list'),
    path('updates/create/', views.ProjectUpdateCreateView.as_view(), name='project_update_create'),
    path('updates/<int:pk>/', views.ProjectUpdateDetailView.as_view(), name='project_update_detail'),
    path('updates/<int:pk>/edit/', views.ProjectUpdateUpdateView.as_view(), name='project_update_update'),
    path('updates/<int:pk>/publish/', views.ProjectUpdatePublishView.as_view(), name='project_update_publish'),
    path('updates/<int:update_pk>/review/create/', views.ProjectUpdateReviewCreateView.as_view(), name='project_update_review_create'),
    path('update-reviews/<int:pk>/', views.ProjectUpdateReviewDetailView.as_view(), name='project_update_review_detail'),
    path('update-reviews/<int:review_pk>/decision/create/', views.ProjectUpdateReviewDecisionCreateView.as_view(), name='project_update_review_decision_create'),
    path('review-decisions/<int:pk>/', views.ProjectUpdateReviewDecisionDetailView.as_view(), name='project_update_review_decision_detail'),
    path('review-decisions/<int:decision_pk>/remediation/create/', views.ProjectUpdateRemediationCreateView.as_view(), name='project_update_remediation_create'),
    path('remediations/<int:pk>/', views.ProjectUpdateRemediationDetailView.as_view(), name='project_update_remediation_detail'),
    path('remediations/<int:pk>/edit/', views.ProjectUpdateRemediationUpdateView.as_view(), name='project_update_remediation_update'),
    path('remediations/<int:pk>/submit/', views.ProjectUpdateRemediationSubmitView.as_view(), name='project_update_remediation_submit'),
    path('remediations/<int:pk>/resolve/', views.ProjectUpdateRemediationResolveView.as_view(), name='project_update_remediation_resolve'),
    path('remediations/<int:pk>/attachments/create/', views.ProjectUpdateRemediationAttachmentCreateView.as_view(), name='project_update_remediation_attachment_create'),
    path('remediation-attachments/<int:pk>/delete/', views.ProjectUpdateRemediationAttachmentDeleteView.as_view(), name='project_update_remediation_attachment_delete'),
    path(
        'remediations/<int:remediation_pk>/attachments/<int:pk>/preview/',
        views.ProjectUpdateRemediationAttachmentPreviewView.as_view(),
        name='project_update_remediation_attachment_preview',
    ),
    path(
        'remediations/<int:remediation_pk>/attachments/<int:pk>/download/',
        views.ProjectUpdateRemediationAttachmentDownloadView.as_view(),
        name='project_update_remediation_attachment_download',
    ),
    path('projects/<int:project_pk>/documents/create/', views.ProjectDocumentCreateView.as_view(), name='project_document_create'),
    path(
        'projects/<int:project_pk>/documents/<int:pk>/preview/',
        views.ProjectDocumentPreviewView.as_view(),
        name='project_document_preview',
    ),
    path(
        'projects/<int:project_pk>/documents/<int:pk>/download/',
        views.ProjectDocumentDownloadView.as_view(),
        name='project_document_download',
    ),
    path('project-documents/<int:pk>/delete/', views.ProjectDocumentDeleteView.as_view(), name='project_document_delete'),
    path('updates/<int:update_pk>/attachments/create/', views.ProjectUpdateAttachmentCreateView.as_view(), name='project_update_attachment_create'),
    path(
        'projects/<int:project_pk>/updates/<int:update_pk>/attachments/<int:pk>/preview/',
        views.ProjectUpdateAttachmentPreviewView.as_view(),
        name='project_update_attachment_preview',
    ),
    path(
        'projects/<int:project_pk>/updates/<int:update_pk>/attachments/<int:pk>/download/',
        views.ProjectUpdateAttachmentDownloadView.as_view(),
        name='project_update_attachment_download',
    ),
    path('update-attachments/<int:pk>/delete/', views.ProjectUpdateAttachmentDeleteView.as_view(), name='project_update_attachment_delete'),
    path('updates/<int:pk>/delete/', views.ProjectUpdateDeleteView.as_view(), name='project_update_delete'),
    path('donations/', views.DonationListView.as_view(), name='donation_list'),
    path('donations/export.csv', views.DonationCsvExportView.as_view(), name='donation_export_csv'),
    path('donations/new/', views.DonationCreateView.as_view(), name='donation_create'),
    path('donations/<int:pk>/', views.DonationDetailView.as_view(), name='donation_detail'),
    path('donations/<int:pk>/edit/', views.DonationUpdateView.as_view(), name='donation_update'),
    path('donations/<int:pk>/delete/', views.DonationDeleteView.as_view(), name='donation_delete'),
    path('donations/<int:pk>/annul/', views.DonationAnnulView.as_view(), name='donation_annul'),
    path('donations/<int:pk>/status/<str:target_status>/', views.DonationStatusTransitionView.as_view(), name='donation_status_transition'),
    path('allocations/', views.FundAllocationListView.as_view(), name='allocation_list'),
    path('allocations/export.csv', views.FundAllocationCsvExportView.as_view(), name='allocation_export_csv'),
    path('allocations/new/', views.FundAllocationCreateView.as_view(), name='allocation_create'),
    path('allocations/<int:pk>/', views.FundAllocationDetailView.as_view(), name='allocation_detail'),
    path('allocations/<int:pk>/edit/', views.FundAllocationUpdateView.as_view(), name='allocation_update'),
    path('allocations/<int:pk>/delete/', views.FundAllocationDeleteView.as_view(), name='allocation_delete'),
    path('allocations/<int:pk>/annul/', views.FundAllocationAnnulView.as_view(), name='allocation_annul'),
    path('allocations/<int:pk>/status/<str:target_status>/', views.FundAllocationStatusTransitionView.as_view(), name='allocation_status_transition'),
    path(
        'expense-requests/',
        views.ExpenseRequestListView.as_view(),
        name='expense_request_list',
    ),
    path(
        'expense-requests/<int:pk>/',
        views.ExpenseRequestDetailView.as_view(),
        name='expense_request_detail',
    ),
    path('expenses/', views.ExpenseListView.as_view(), name='expense_list'),
    path('expenses/export.csv', views.ExpenseCsvExportView.as_view(), name='expense_export_csv'),
    path('expenses/new/', views.ExpenseCreateView.as_view(), name='expense_create'),
    path('expenses/<int:pk>/', views.ExpenseDetailView.as_view(), name='expense_detail'),
    path('expenses/<int:pk>/edit/', views.ExpenseUpdateView.as_view(), name='expense_update'),
    path('expenses/<int:pk>/delete/', views.ExpenseDeleteView.as_view(), name='expense_delete'),
    path('expenses/<int:pk>/annul/', views.ExpenseAnnulView.as_view(), name='expense_annul'),
    path(
        'expenses/<int:expense_pk>/documents/create/',
        views.SupportingDocumentCreateForExpenseView.as_view(),
        name='supporting_document_create_for_expense',
    ),
    path(
        'expenses/<int:expense_pk>/documents/<int:pk>/preview/',
        views.SupportingDocumentPreviewView.as_view(),
        name='supporting_document_preview',
    ),
    path(
        'expenses/<int:expense_pk>/documents/<int:pk>/download/',
        views.SupportingDocumentDownloadView.as_view(),
        name='supporting_document_download',
    ),
    path(
        'projects/<int:project_pk>/supporting-documents/<int:pk>/preview/',
        views.ProjectSupportingDocumentPreviewView.as_view(),
        name='project_supporting_document_preview',
    ),
    path(
        'projects/<int:project_pk>/supporting-documents/<int:pk>/download/',
        views.ProjectSupportingDocumentDownloadView.as_view(),
        name='project_supporting_document_download',
    ),
    path(
        'documents/<int:pk>/delete/',
        views.SupportingDocumentDeleteView.as_view(),
        name='supporting_document_delete',
    ),
    path('audit/', views.AuditLogListView.as_view(), name='audit_log_list'),
]
