# Generated by Django 6.0.6 on 2026-07-09 20:44

import django.db.models.deletion
import django_countries.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('donation_type', models.CharField(choices=[('goods', 'Bienes'), ('kits', 'Kits'), ('food', 'Alimentos'), ('medicine', 'Medicinas'), ('equipment', 'Equipos'), ('tools', 'Herramientas'), ('services', 'Servicios'), ('materials', 'Materiales')], default='goods', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('VES', 'Bolívar venezolano'), ('COP', 'Peso colombiano')], default='USD', max_length=3)),
                ('objective', models.TextField()),
                ('restrictions', models.TextField(blank=True)),
                ('commitment_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registrada'), ('committed', 'Comprometida'), ('received', 'Recibida'), ('partially_allocated', 'Asignada parcialmente'), ('fully_allocated', 'Asignada totalmente'), ('closed', 'Cerrada'), ('annulled', 'Anulada')], default='registered', max_length=30)),
                ('support_reference', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'donación',
                'verbose_name_plural': 'donaciones',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('institution_type', models.CharField(choices=[('archdiocese', 'Arquidiócesis'), ('parish', 'Parroquia'), ('foundation', 'Fundación'), ('ngo', 'ONG'), ('company', 'Empresa'), ('public_entity', 'Entidad pública'), ('international_organization', 'Organización internacional'), ('other', 'Otra')], max_length=40)),
                ('role', models.CharField(choices=[('donor', 'Donante'), ('receiver', 'Receptora'), ('executor', 'Ejecutora'), ('ally', 'Aliada'), ('supervisor', 'Supervisora')], max_length=20)),
                ('country', django_countries.fields.CountryField(default='VE', max_length=2, verbose_name='País')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=60)),
                ('responsible_person', models.CharField(blank=True, max_length=120)),
                ('legal_document', models.FileField(blank=True, upload_to='institution_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'institución',
                'verbose_name_plural': 'instituciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('responsible_unit', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('closed', 'Cerrado'), ('annulled', 'Anulado')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('validated', 'Validada'), ('rejected', 'Rechazada'), ('annulled', 'Anulada'), ('assigned', 'Asignada'), ('executed', 'Ejecutada'), ('closed', 'Cerrada')], max_length=20)),
                ('model_name', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('entity_label', models.CharField(max_length=220)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_category', models.CharField(choices=[('infrastructure_supply', 'Infraestructura y Abasto local'), ('health_psychosocial', 'Salud y apoyo psicosocial'), ('training_entrepreneurship', 'Formación y emprendimiento'), ('communication_networks', 'Redes de comunicación'), ('institutional_relations', 'Relaciones institucionales')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('responsible_person', models.CharField(blank=True, max_length=120)),
                ('allocation_date', models.DateField()),
                ('status', models.CharField(choices=[('created', 'Creada'), ('active', 'En ejecución'), ('partially_executed', 'Ejecutada parcialmente'), ('fully_executed', 'Ejecutada totalmente'), ('closed', 'Cerrada'), ('annulled', 'Anulada')], default='created', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='operations.donation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='operations.project')),
            ],
            options={
                'verbose_name': 'asignación de fondos',
                'verbose_name_plural': 'asignaciones de fondos',
                'ordering': ['-allocation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('food', 'Alimentos'), ('medicine', 'Medicinas'), ('equipment', 'Equipos'), ('transport', 'Transporte'), ('logistics', 'Logística'), ('services', 'Servicios'), ('materials', 'Materiales'), ('other', 'Otra')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('VES', 'Bolívar venezolano'), ('COP', 'Peso colombiano')], default='USD', max_length=3)),
                ('reason', models.CharField(max_length=220)),
                ('provider_or_recipient', models.CharField(max_length=160)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Transferencia bancaria'), ('cash', 'Efectivo'), ('mobile_payment', 'Pago móvil'), ('card', 'Tarjeta'), ('check', 'Cheque'), ('other', 'Otro')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registered', 'Registrado'), ('in_review', 'En revisión'), ('validated', 'Validado'), ('rejected', 'Rechazado'), ('annulled', 'Anulado')], default='registered', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_expenses', to=settings.AUTH_USER_MODEL)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='operations.fundallocation')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='operations.institution'),
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('document', models.FileField(upload_to='supporting_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='operations.expense')),
            ],
            options={
                'verbose_name': 'documento soporte',
                'verbose_name_plural': 'documentos soporte',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
