# Generated by Django 6.0.6 on 2026-07-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_projectupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('money', 'Dinero'), ('goods', 'Bienes'), ('kits', 'Kits'), ('food', 'Alimentos'), ('medicine', 'Medicinas'), ('equipment', 'Equipos'), ('tools', 'Herramientas'), ('services', 'Servicios'), ('materials', 'Materiales')], default='goods', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Transferencia bancaria'), ('cash', 'Efectivo'), ('card', 'Tarjeta'), ('check', 'Cheque'), ('other', 'Otro')], max_length=40),
        ),
    ]
