# Generated by Django 6.0.6 on 2026-07-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_donation_donation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('validated', 'Validada'), ('rejected', 'Rechazada'), ('annulled', 'Anulada'), ('assigned', 'Asignada'), ('executed', 'Ejecutada'), ('closed', 'Cerrada'), ('expense_cancelled', 'Gasto anulado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('registered', 'Registrado'), ('in_review', 'En revisión'), ('validated', 'Validado'), ('rejected', 'Rechazado'), ('annulled', 'Anulado'), ('cancelled', 'Anulado')], default='registered', max_length=20),
        ),
    ]
