# Generated by Django 6.0.6 on 2026-07-11 11:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_auditlog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='operations_donation_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='operations_expense_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='fundallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='operations_allocation_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_budget__gte', Decimal('0.00'))), name='operations_project_budget_gte_zero'),
        ),
    ]
