# Generated by Django 6.0.6 on 2026-07-11 20:43

import re

from django.db import migrations, models


CODE_DEFINITIONS = {
    'project': ('Project', 'PRJ'),
    'donation': ('Donation', 'DON'),
    'fund_allocation': ('FundAllocation', 'ASG'),
    'expense': ('Expense', 'GAS'),
}


# PRE: schema contains nullable allocation/expense codes and the sequence table.
# POST: preserves existing codes, fills missing codes by pk, and initializes every next value.
def populate_operational_codes(apps, schema_editor):
    sequence_model = apps.get_model('operations', 'OperationalCodeSequence')

    for namespace, (model_name, prefix) in CODE_DEFINITIONS.items():
        model = apps.get_model('operations', model_name)
        valid_code = re.compile(rf'^{prefix}-(\d{{6}})$')
        highest_value = 0
        existing_codes = model.objects.exclude(code__isnull=True).exclude(code='')
        for code in existing_codes.values_list('code', flat=True):
            match = valid_code.fullmatch(code)
            if match:
                highest_value = max(highest_value, int(match.group(1)))

        if model_name in {'FundAllocation', 'Expense'}:
            for instance in model.objects.filter(code__isnull=True).order_by('pk').iterator():
                highest_value += 1
                instance.code = f'{prefix}-{highest_value:06d}'
                instance.save(update_fields=('code',))

        sequence_model.objects.update_or_create(
            namespace=namespace,
            defaults={'prefix': prefix, 'next_value': highest_value + 1},
        )


def preserve_operational_codes_on_reverse(apps, schema_editor):
    # Codes are durable human identifiers and must never be cleared on reverse migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_monetary_row_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalCodeSequence',
            fields=[
                ('namespace', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=3, unique=True)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'secuencia de código operativo',
                'verbose_name_plural': 'secuencias de códigos operativos',
            },
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.RunPython(
            populate_operational_codes,
            preserve_operational_codes_on_reverse,
        ),
        migrations.AlterField(
            model_name='fundallocation',
            name='code',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='code',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
