# Generated by Django 6.0.6 on 2026-07-11 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_operational_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='terminal_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='terminal_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='terminal_reason',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='terminal_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='terminal_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='terminal_reason',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='terminal_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='terminal_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='terminal_reason',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
