# Generated by Django 5.2 on 2026-07-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_projectupdatereviewdecision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupdate',
            options={
                'ordering': ['-created_at'],
                'permissions': [('publish_projectupdate', 'Puede publicar avances de proyecto')],
                'verbose_name': 'avance de proyecto',
                'verbose_name_plural': 'avances de proyecto',
            },
        ),
        migrations.AlterModelOptions(
            name='projectupdatereview',
            options={
                'ordering': ['-reviewed_at'],
                'permissions': [('review_projectupdate', 'Puede registrar revisiones de avances')],
                'verbose_name': 'revisión documental de avance',
                'verbose_name_plural': 'revisiones documentales de avances',
            },
        ),
        migrations.AlterModelOptions(
            name='projectupdatereviewdecision',
            options={
                'ordering': ['-decided_at'],
                'permissions': [('decide_projectupdate', 'Puede registrar decisiones institucionales de avances')],
                'verbose_name': 'resultado de revisión del Comité',
                'verbose_name_plural': 'resultados de revisiones del Comité',
            },
        ),
    ]
