# Generated by Django 6.0.6 on 2026-07-14 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_alter_projectupdate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdateRemediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_update_remediations', to=settings.AUTH_USER_MODEL)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='remediation', to='operations.projectupdatereviewdecision')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_project_update_remediations', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_project_update_remediations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'remediación de avance',
                'verbose_name_plural': 'remediaciones de avances',
                'ordering': ['-created_at'],
                'permissions': [('submit_projectupdateremediation', 'Puede enviar remediaciones de avances'), ('resolve_projectupdateremediation', 'Puede resolver remediaciones de avances')],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdateRemediationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_update_remediation_attachments/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.projectupdateremediation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_update_remediation_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adjunto de remediación',
                'verbose_name_plural': 'adjuntos de remediaciones',
                'ordering': ['created_at'],
            },
        ),
    ]
