# Generated by Django 6.0.6

from django.db import migrations


AUDITLOG_TABLE = "operations_auditlog"
AUDITLOG_TRIGGER_FUNCTION = "operations_auditlog_reject_mutation"
AUDITLOG_TRIGGER_NAME = "operations_auditlog_append_only"

# PRE: statement fires BEFORE UPDATE/DELETE/TRUNCATE on operations_auditlog.
# POST: raises a safe, generic error without leaking row contents; INSERT and
# SELECT are never intercepted because this trigger does not fire for them.
INSTALL_FUNCTION_SQL = f"""
CREATE OR REPLACE FUNCTION {AUDITLOG_TRIGGER_FUNCTION}()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'operations_auditlog es append-only: UPDATE, DELETE y TRUNCATE estan prohibidos.'
        USING ERRCODE = 'restrict_violation';
END;
$$;
"""

DROP_TRIGGER_SQL = (
    f"DROP TRIGGER IF EXISTS {AUDITLOG_TRIGGER_NAME} ON {AUDITLOG_TABLE};"
)

# FOR EACH STATEMENT is required because TRUNCATE has no per-row semantics;
# combining UPDATE/DELETE/TRUNCATE in one statement-level trigger keeps a
# single, explicit defense point for every rejected mutation.
INSTALL_TRIGGER_SQL = f"""
CREATE TRIGGER {AUDITLOG_TRIGGER_NAME}
BEFORE UPDATE OR DELETE OR TRUNCATE ON {AUDITLOG_TABLE}
FOR EACH STATEMENT
EXECUTE FUNCTION {AUDITLOG_TRIGGER_FUNCTION}();
"""

DROP_FUNCTION_SQL = f"DROP FUNCTION IF EXISTS {AUDITLOG_TRIGGER_FUNCTION}();"


def install_append_only_trigger(apps, schema_editor):
    """
    PRE: operations_auditlog exists in the target database.
    POST: on PostgreSQL, installs (idempotently) the function and trigger that
    reject UPDATE/DELETE/TRUNCATE. On other backends this is a deliberate
    no-op so `migrate` keeps working for SQLite local development.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(INSTALL_FUNCTION_SQL)
    schema_editor.execute(DROP_TRIGGER_SQL)
    schema_editor.execute(INSTALL_TRIGGER_SQL)


def remove_append_only_trigger(apps, schema_editor):
    """
    PRE: install_append_only_trigger may or may not have run on this backend.
    POST: on PostgreSQL, drops the trigger before the function it depends on.
    No-op on other backends.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DROP_TRIGGER_SQL)
    schema_editor.execute(DROP_FUNCTION_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0017_projectupdateremediation_and_more"),
    ]

    operations = [
        migrations.RunPython(
            install_append_only_trigger,
            remove_append_only_trigger,
            elidable=False,
        ),
    ]
