# Generated by Django 6.0.6 on 2026-07-15 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_auditlog_append_only_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='operations_donation_currency_is_usd'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='operations_expense_currency_is_usd'),
        ),
    ]
