# Generated by Django 6.0.6 on 2026-07-16 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_enforce_usd_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('validated', 'Validada'), ('rejected', 'Rechazada'), ('annulled', 'Anulada'), ('assigned', 'Asignada'), ('executed', 'Ejecutada'), ('closed', 'Cerrada'), ('expense_cancelled', 'Gasto anulado'), ('published', 'Publicada'), ('completed', 'Completada'), ('reopened', 'Reabierta'), ('reordered', 'Reordenada'), ('deleted', 'Eliminada')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_project_milestones', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_milestones', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='operations.project')),
            ],
            options={
                'verbose_name': 'hito de proyecto',
                'verbose_name_plural': 'hitos de proyecto',
                'ordering': ('position', 'pk'),
                'permissions': (('complete_projectmilestone', 'Puede completar o reabrir hitos de proyecto'), ('reorder_projectmilestone', 'Puede reordenar hitos de proyecto')),
                'constraints': [models.UniqueConstraint(fields=('project', 'position'), name='unique_project_milestone_position'), models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='project_milestone_position_gte_1'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('is_completed', False)), models.Q(('completed_at__isnull', False), ('is_completed', True)), _connector='OR'), name='project_milestone_completion_consistency')],
            },
        ),
    ]
