# Generated by Django 6.0.6 on 2026-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_alter_auditlog_action_projectmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('closed', 'Cerrado')], default='active', max_length=20),
        ),
    ]
