# Generated by Django 6.0.6 on 2026-07-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_project_lifecycle_active_closed_and_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['code'], 'permissions': [('manage_project_publication', 'Puede publicar y retirar proyectos del portal público')], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('validated', 'Validada'), ('rejected', 'Rechazada'), ('annulled', 'Anulada'), ('assigned', 'Asignada'), ('executed', 'Ejecutada'), ('closed', 'Cerrada'), ('expense_cancelled', 'Gasto anulado'), ('published', 'Publicada'), ('unpublished', 'Retirado del portal'), ('completed', 'Completada'), ('reopened', 'Reabierta'), ('reordered', 'Reordenada'), ('deleted', 'Eliminada')], max_length=20),
        ),
    ]
