# Generated by Django 6.0.6 on 2026-08-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_project_publication_permission_and_audit_unpublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='responsible_unit',
        ),
    ]
