# Generated by Django 6.0.6 on 2026-08-01 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_remove_project_responsible_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectupdate',
            name='project_update_progress_between_0_and_100',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='progress_percentage',
        ),
    ]
