# Generated by Django 6.0.6 on 2026-08-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_remove_projectupdate_progress_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='status',
            field=models.CharField(choices=[('unpublished', 'No publicado'), ('published', 'Publicado')], default='unpublished', max_length=30),
        ),
    ]
