# Generated by Django 6.0.6 on 2026-08-01 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_rename_projectupdate_draft_to_unpublished'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purpose', models.CharField(max_length=220)),
                ('requested_date', models.DateField()),
                ('status', models.CharField(choices=[('pending_decision', 'Pendiente de decisión'), ('approved_reserved', 'Aprobada · Fondos reservados'), ('denied', 'Denegada'), ('withdrawn', 'Retirada'), ('fulfilled', 'Gasto registrado'), ('annulled', 'Anulada')], default='pending_decision', max_length=30)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reserved_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('reserved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('terminal_reason', models.TextField(blank=True, editable=False)),
                ('terminal_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_expense_requests', to=settings.AUTH_USER_MODEL)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_expense_request', to='operations.expense')),
                ('fund_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='operations.fundallocation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to=settings.AUTH_USER_MODEL)),
                ('terminal_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_expense_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de gasto',
                'verbose_name_plural': 'solicitudes de gasto',
                'ordering': ['-requested_date', '-created_at'],
                'permissions': [('decide_expenserequest', 'Puede aprobar o denegar solicitudes de gasto'), ('fulfill_expenserequest', 'Puede registrar el gasto de una solicitud aprobada'), ('withdraw_expenserequest', 'Puede retirar solicitudes de gasto propias'), ('annul_expenserequest', 'Puede anular solicitudes de gasto')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expense_request_attachments/%Y/%m/')),
                ('title', models.CharField(max_length=160)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('expense_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.expenserequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_expense_request_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adjunto de solicitud de gasto',
                'verbose_name_plural': 'adjuntos de solicitudes de gasto',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Solicitud creada'), ('updated', 'Solicitud actualizada'), ('withdrawn', 'Solicitud retirada'), ('approved', 'Solicitud aprobada'), ('denied', 'Solicitud denegada'), ('reservation_created', 'Reserva creada'), ('annulled', 'Solicitud anulada'), ('reservation_released', 'Reserva liberada'), ('expense_registered', 'Gasto registrado'), ('reservation_consumed', 'Reserva convertida en ejecución'), ('unused_reservation_released', 'Reserva no utilizada liberada'), ('linked_expense_annulled', 'Gasto enlazado anulado')], max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reserved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('executed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('released_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('allocation_balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocation_balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_request_events', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_request_events', to='operations.expense')),
                ('expense_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operations.expenserequest')),
            ],
            options={
                'verbose_name': 'evento de solicitud de gasto',
                'verbose_name_plural': 'eventos de solicitudes de gasto',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['status'], name='ops_expreq_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['fund_allocation', 'status'], name='ops_expreq_alloc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['requested_by', 'status'], name='ops_expreq_req_by_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['-requested_date'], name='ops_expreq_req_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['-decided_at'], name='ops_expreq_decided_at_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['-created_at'], name='ops_expreq_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequestevent',
            index=models.Index(fields=['expense_request', 'created_at'], name='ops_expreq_evt_req_created_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequestevent',
            index=models.Index(fields=['event_type', 'created_at'], name='ops_expreq_evt_type_crtd_idx'),
        ),
    ]
