# Generated by Django 6.0.6 on 2026-08-01 21:39

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_expense_request_models'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(('requested_amount__gt', Decimal('0.00'))),
                name='operations_expenserequest_requested_amount_gt_zero',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('reserved_amount__isnull', True),
                    ('reserved_amount__gte', Decimal('0.00')),
                    _connector='OR',
                ),
                name='operations_expenserequest_reserved_amount_gte_zero',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('reserved_amount__isnull', True),
                    ('reserved_amount__lte', models.F('requested_amount')),
                    _connector='OR',
                ),
                name='operations_expenserequest_reserved_lte_requested',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status', 'fulfilled'), _negated=True),
                    ('expense__isnull', False),
                    _connector='OR',
                ),
                name='operations_expenserequest_fulfilled_requires_expense',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('status', 'fulfilled'),
                    ('expense__isnull', True),
                    _connector='OR',
                ),
                name='operations_expenserequest_non_fulfilled_no_expense',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status__in', ['approved_reserved', 'fulfilled']), _negated=True),
                    models.Q(
                        ('decided_by__isnull', False),
                        ('decided_at__isnull', False),
                        ('reserved_amount__isnull', False),
                        ('reserved_at__isnull', False),
                    ),
                    _connector='OR',
                ),
                name='operations_expenserequest_approved_fulfilled_meta',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status', 'denied'), _negated=True),
                    models.Q(
                        ('decided_by__isnull', False),
                        ('decided_at__isnull', False),
                        models.Q(('decision_note', ''), _negated=True),
                    ),
                    _connector='OR',
                ),
                name='operations_expenserequest_denied_requires_decision',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status__in', ['withdrawn', 'annulled']), _negated=True),
                    models.Q(
                        ('terminal_by__isnull', False),
                        ('terminal_at__isnull', False),
                        models.Q(('terminal_reason', ''), _negated=True),
                    ),
                    _connector='OR',
                ),
                name='operations_expenserequest_terminal_requires_meta',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status', 'pending_decision'), _negated=True),
                    models.Q(
                        ('decided_by__isnull', True),
                        ('decided_at__isnull', True),
                        ('decision_note', ''),
                        ('reserved_amount__isnull', True),
                        ('reserved_at__isnull', True),
                        ('expense__isnull', True),
                        ('terminal_by__isnull', True),
                        ('terminal_at__isnull', True),
                        ('terminal_reason', ''),
                    ),
                    _connector='OR',
                ),
                name='operations_expenserequest_pending_clean_slate',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status', 'denied'), _negated=True),
                    models.Q(
                        ('reserved_amount__isnull', True),
                        ('reserved_at__isnull', True),
                        ('expense__isnull', True),
                        ('terminal_by__isnull', True),
                        ('terminal_at__isnull', True),
                        ('terminal_reason', ''),
                    ),
                    _connector='OR',
                ),
                name='operations_expenserequest_denied_no_reservation',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status', 'withdrawn'), _negated=True),
                    models.Q(
                        ('decided_by__isnull', True),
                        ('decided_at__isnull', True),
                        ('decision_note', ''),
                        ('reserved_amount__isnull', True),
                        ('reserved_at__isnull', True),
                        ('expense__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='operations_expenserequest_withdrawn_no_decision',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status', 'approved_reserved'), _negated=True),
                    models.Q(
                        ('expense__isnull', True),
                        ('terminal_by__isnull', True),
                        ('terminal_at__isnull', True),
                        ('terminal_reason', ''),
                    ),
                    _connector='OR',
                ),
                name='operations_expenserequest_approved_no_terminal',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status', 'fulfilled'), _negated=True),
                    models.Q(
                        ('terminal_by__isnull', True),
                        ('terminal_at__isnull', True),
                        ('terminal_reason', ''),
                    ),
                    _connector='OR',
                ),
                name='operations_expenserequest_fulfilled_no_terminal',
            ),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('status', 'annulled'), _negated=True),
                    ('expense__isnull', True),
                    _connector='OR',
                ),
                name='operations_expenserequest_annulled_no_expense',
            ),
        ),
    ]
