# Generated by Django 6.0.6 on 2026-08-02 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_expense_request_event_append_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequestevent',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_request_events', to='operations.expense'),
        ),
    ]
