# Generated by Django 6.0.6 on 2026-08-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_projectupdateattachment_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundallocation',
            name='budget_category',
            field=models.CharField(choices=[('infrastructure_supply', 'Infraestructura y abasto local'), ('health_psychosocial', 'Salud y apoyo psicosocial'), ('training_entrepreneurship', 'Formación y emprendimiento'), ('communication_networks', 'Redes de comunicación'), ('institutional_relations', 'Relaciones institucionales')], max_length=40),
        ),
    ]
